### ISSUE TITLE
Filtering by SourceContext property is impossible using decorators

### ISSUE THREAD

**Issue by iloktionov** [vostok/logging.abstractions#4]
This issue arises due to filters being decorators over ILog instances while `ForContext()` calls propagate all the way down to the implementation. 

Repro (following code is not expected to print anything):
```
new SynchronousConsoleLog()
    .DropEvents(evt => evt.Properties?[WellKnownProperties.SourceContext] == "foo")
    .ForContext("foo")
    .Info("Hello!");
```

**Comment by shumantt** [comment]
Are there any workarounds to filter events by SourceContext now?
